stages:
  - build_and_deploy

deploy:
  image: node:15
  stage: build_and_deploy

  before_script:
    - yarn install

  script:
    - yarn build
    - cat $IPFS_DEPLOY_ENV_FILE > .env
    - yarn deploy:ipfs -p $IPFS_PROVIDER -d $IPFS_DNS_RESOLVER

  only:
    - master
