stages:
  - build
  - release
  - deploy

build:
  image: node:15
  stage: build

  before_script:
    - yarn install

  script:
    - yarn build

  artifacts:
    paths:
      - dist/


publish_npm_release:
  image: node:15
  stage: release

  before_script:
    - yarn install

  script:
    - yarn build
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
    - npm publish

  when:
    - tags

  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+-release$/'

deploy:
  image: node:15
  stage: deploy

  before_script:
    - yarn install

  script:
    - cat $IPFS_DEPLOY_ENV_FILE > .env
    - yarn deploy:ipfs -p $IPFS_PROVIDER -d $IPFS_DNS_RESOLVER

  dependencies:
    - build

  when: manual
