stages:
  - publish

pages:
  stage: publish
  image: node:15

  before_script:
    - yarn install

  script:
    - yarn build
    - mv public .public
    - mv dist public

  artifacts:
    paths:
      - public

  only:
    - master
